spring:
  datasource:
    url: jdbc:h2:mem:H2DB;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      path: /h2-ui
      enabled: true
  jpa:
    properties:
      hibernate:
        transaction:
          jta:
            platform: com.atomikos.icatch.jta.hibernate4.AtomikosPlatform
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: true
